### ISSUE TITLE
Add coverage for dynamic import

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#1164]
currently on stage 3.

https://github.com/tc39/proposal-dynamic-import

# Coverage Checklist for `import()`

## Default Templates

_general places it can be found as a CallExpression_

- [x] top level
- [x] consise body of an ArrowFunction
- [x] function body of an ArrowFunction
- [x] consise body of an __Async__ ArrowFunction
- [x] function body of an __Async__ ArrowFunction
- [x] Used in async generators
- [x] await position of an async function
- [x] return await position of an async function
- [x] nested in an async function
- [x] labeled blocks
- [x] blocks
- [x] do while
- [x] else braceless
- [x] else block
- [x] if braceless
- [x] if block
- [x] while block
- [x] inside `with`

### Syntax

- [x] assignment expression is not optional `assignment-expr-not-optional.case`
- [x] empty string is a valid assignment expression (not a syntax error) `empty-str-is-valid-assign-expr.case`
- [x] _Forbidden Extensions: ImportCall must not be extended._ (Only one assignment expression allowed)
    - [x] no trailing comma, it's not an arguments list (#1832)
    - [x] no other expressions (#1832)

### Common usage

- [x] indirect update default binding `eval-gtbndng-indirect-update-dflt.case`
- [x] indirect update named binding `eval-gtbndng-indirect-update-dflt.case`
- [x] Assignment Expression evaluations. Most can be used as syntax tests only, e.g. exprs evaluating to a boolean value) or error catching
    - [x] ConditionalExpression
        - [x] Primary Expressions on the import Assign. Expr. position (?)
        - [x] Cover Parenthesis expressions
        - [x] ...
    - [x] YieldExpression
        - [x] Check yield usage
    - [x] ArrowFunction
    - [x] AsyncArrowFunction
    - [x] LeftHandSideExpression = AssignmentExpression
    - [x] LeftHandSideExpression AssignmentOperator AssignmentExpression
- [x] ToString on the AssignmentExpression value `Let specifierString be ToString(specifier).`
    - [ ] `If AbruptRejectPromise(specifierString, promiseCapability).`
- [ ] nest `import()` in CallExpressions
    - [x] `import(import(...))` (#1832)
    - [ ] ... (other CallExpressions here)
- [x] Goal target can be a script code (not module code)
    - [x] in this case, it should not export anything (and it's not a SyntaxError like in static imports)
    - [ ] indirect updates
- [x] Goal target can be a module code (having module specific syntax)
- [x] module code on host syntax
- [x] Multiple imports on the same imported module
    - [x] verify indirect updates
    - [x] Imported module is only evaluated once. `test/language/module-code/dynamic-import/eval-rqstd-once.js`
    - [x] Self loading module only evaluates once. `test/language/module-code/dynamic-import/eval-self-once-module.js`
    - [x] Self loading script evaluates again once for `import()`. `test/language/module-code/dynamic-import/eval-self-once-script.js`
- [x] ImportCall in runtime returns a Promise
    - [x] Verify ctor
    - [x] Use in Promise.all?
    - [x] await resolving (include failures)
    - [x] Use Promise.prototype
    - [ ] Promise.resolve
- [x] Captures exported operations of `.. in ..` in exported values. `test/language/module-code/dynamic-import/eval-export-dflt-expr-in.js`
- [x] Does not create a default property if default export is not given
- [x] imported value is an object with the exported names, including default
- [x] Returns abrupt completion from GetValue on AssignmentExpression (not a promise reject)
- [x] ToString on specifier
  - [x] Abrupt completions should reject the promise

### Resolve Moduled Namespace object

- [x] Symbol.toStringTag
- [x] no Symbol.iterator
- [x] prop desc of imported names
- [x] imported symbols on own property keys internals
- [x] internals https://tc39.github.io/ecma262/#sec-module-namespace-exotic-objects
- [x] setting custom immutable prototype
- [x] prototype is null
- [x] References observe the mutation of initialized bindings ([[Get]] on bindings after changing their values)
- [ ] The [[OwnPropertyKeys]] internal method includes entries for all binding types

### Non generated tests

- [x] Self importing test files
    - [x] default name binding `test/language/module-code/dynamic-import/eval-export-dflt-cls-anon.js`
    - [x] `test/language/module-code/dynamic-import/eval-export-dflt-cls-name-meth.js`
    - [x] `test/language/module-code/dynamic-import/eval-export-dflt-cls-named.js`
    - [x] `test/language/module-code/dynamic-import/eval-export-dflt-expr-cls-anon.js`
    - [x] `test/language/module-code/dynamic-import/eval-export-dflt-expr-cls-name-meth.js`
    - [x] `test/language/module-code/dynamic-import/eval-export-dflt-expr-cls-named.js`
    - [x] `test/language/module-code/dynamic-import/eval-export-dflt-expr-fn-anon.js`
    - [x] `test/language/module-code/dynamic-import/eval-export-dflt-expr-fn-named.js`
    - [x] `test/language/module-code/dynamic-import/eval-export-dflt-expr-gen-anon.js`
    - [x] `test/language/module-code/dynamic-import/eval-export-dflt-expr-gen-named.js`

### Error catching

- [x] resolved runtime error (TypeError) `eval-rqstd-abrupt-typeerror.case`
- [x] resolved runtime error (URIError) `eval-rqstd-abrupt-urierror.case`
- [x] ambiguous import
- [x] circular import error
- [x] File does not exist (#1832)

**Comment by leobalter** [comment]
This has found a sufficient amount of tests. Test262 is still welcoming to further coverage if any is observed.
