### ISSUE TITLE
Test Coverage Audit and Tracking for Atomics.wait

### ISSUE THREAD

**Issue by nomadtechie** [tc39/test262#1466]
Below is a checklist for the observable items in the `Atomics.wait` spec: https://tc39.github.io/ecma262/#sec-atomics.wait. 

I've mapped and noted the coverage of the current *13 tests* and will be adding coverage for the remaining observables. I'll also be refactoring a few of the current tests because they cover too many spec observables in one test file.

Some of the observables I've listed below may not be directly testable via test262. I'll keep this list updated as I find unobservable abstractions and will mark  them as **NOT DIRECTLY OBSERVABLE**

### Atomics built-in

- [x] @@toStringTag property is the String value "Atomics" & property has the attributes { [[Writable]]: false, [[Enumerable]]: false, [[Configurable]]: true }
  - test/built-ins/Atomics/Symbol.toStringTag.js
- [x] Is not constructable - does not have a [[Construct]] internal method
  - test/built-ins/Atomics/prop-desc.js
- [x] Is not callable - does not have a [[Call]] internal method
  - test/built-ins/Atomics/prop-desc.js
- [x] The value of the [[Prototype]] internal slot of the Atomics object is the intrinsic object %ObjectPrototype%.
  - test/built-ins/Atomics/proto.js

### Atomics.wait Static Property

- [x] Check Name
  - test/built-ins/Atomics/wait/name.js
- [x] Check length
  - test/built-ins/Atomics/wait/length.js
- [x] Check descriptor
  - test/built-ins/Atomics/wait/descriptor.js

### Atomics.wait(typedArray, index, value, timeout)

1. Let buffer be ? ValidateSharedIntegerTypedArray(typedArray, true)
    - [x] test for abrupt return if ValidateSharedIntegerTypedArray throws an error
      - test/built-ins/Atomics/wait/not-an-object-throws.js
      - test/built-ins/Atomics/wait/non-int32-typedarray-throws.js
      - test/built-ins/Atomics/wait/null-bufferdata-throws.js
      - test/built-ins/Atomics/wait/nonshared-bufferdata-throws.js
      - test/built-ins/Atomics/wait/not-a-typedarray-throws.js
      - _ValidateSharedIntegerTypedArray_:
        - [x] if Type(typedArray) is not Object, throw a TypeError exception
          - test/built-ins/Atomics/wait/not-an-object-throws.js
          - test/built-ins/Atomics/wait/non-views.js
        - [x] If typedArray does not have a [[TypedArrayName]] internal slot, throw a TypeError exception
          - test/built-ins/Atomics/wait/not-a-typedarray-throws.js
        - [x] If typeName is not "Int32Array", throw a TypeError exception.
          - test/built-ins/Atomics/wait/non-int32-typedarray-throws.js
          - test/built-ins/Atomics/wait/shared-nonint-views.js
        - [x] If IsSharedArrayBuffer(buffer) is false, throw a TypeError exception
          - test/built-ins/Atomics/wait/shared-int-views.js
          - _IsSharedArrayBuffer_:
            - [x] If bufferData is null, return false. ( via setting [[ArrayBufferData]] to null)
              - test/built-ins/Atomics/wait/null-bufferdata-throws.js
            - [x] If bufferData is a Data Block, return false. (via creating a Data Block https://tc39.github.io/ecma262/#sec-data-blocks)
              - test/built-ins/Atomics/wait/nonshared-bufferdata-throws.js
2. Let i be ? ValidateAtomicAccess(typedArray, index)
    - [x] test for abrupt return if ValidateAtomicAccess throws an error
        - test/built-ins/Atomics/wait/negative-index-throws.js
        - test/built-ins/Atomics/wait/symbol-for-index-throws.js
        - test/built-ins/Atomics/wait/out-of-range-index-throws.js
        - From _ValidateAtomicAccess_:
          - Let accessIndex be ? ToIndex(requestIndex)
            - [x] abrupt return if ToIndex throws an error
              - test/built-ins/Atomics/wait/symbol-for-index-throws.js
              - test/built-ins/Atomics/wait/negative-index-throws.js
            - From _ToIndex_:
              - [x] If value is undefined, let index be 0 and return index
                - test/built-ins/Atomics/wait/undefined-index-defaults-to-zero.js
              - [x] If integerIndex < 0, throw a RangeError exception.
                - test/built-ins/Atomics/wait/negative-index-throws.js
        - [x] If accessIndex ≥ length, throw a RangeError exception.
          - test/built-ins/Atomics/wait/out-of-range-index-throws.js
          - test/built-ins/Atomics/wait/bad-range.js
3. Let v be ? ToInt32(value)
    - [x] abrupt return if ToInt32 throws an error
      - test/built-ins/Atomics/wait/symbol-for-value-throws.js
    - Let number be ? ToNumber(argument)
      - From _ToNumber_: *(test cases limited to superficial tests which ensure ToNumber is called)*
        - [x] ToNumber(Symbol) --> Throw a TypeError exception.
          - test/built-ins/Atomics/wait/symbol-for-value-throws.js
        - [x] abrupt return if ToNumber throws an error
          - test/built-ins/Atomics/wait/symbol-for-value-throws.js
      - [x] Let int be the mathematical value that is the same sign as number and whose magnitude is floor(abs(number)).
      - [x] If number is NaN, +0, -0, +∞, or -∞, return +0.
      - [x] If int32bit ≥ 231, return int32bit - 232; otherwise return int32bit.
4. Let q be ? ToNumber(timeout)
    - Let number be ? ToNumber(argument)
      - From _ToNumber_: *(test cases limited to superficial tests which ensure ToNumber is called)*
        - [x] ToNumber(Symbol) --> Throw a TypeError exception.
          - test/built-ins/Atomics/wait/symbol-for-timeout-throws.js
        - [x] abrupt return if ToNumber throws an error
          - test/built-ins/Atomics/wait/symbol-for-timeout-throws.js
        TODO- add other tests in here
5. If q is NaN, let t be +∞, else let t be max(q, 0)
    - [x] confirm that passing a negative timeout translates to 0ms
      - test/built-ins/Atomics/wait/negative-timeout.js
    - [x] confirm that passing NaN as a timeout translate to +infinity
      - test/built-ins/Atomics/wait/nan-timeout.js (also implied coverage here test/built-ins/Atomics/wait/was-woken.js)
        - test/built-ins/Atomics/wait/nan-for-timeout.js
        - test/built-ins/Atomics/wait/undefined-for-timeout.js
6. Let B be AgentCanSuspend() *(coverage combined with #7)*
7. If B is false, throw a TypeError exception
    - [x] when [[CanBlock]] is false for an agent: call Atomics.wait on the main thread and expect that it will throw a TypeError since you can not block on the main thread
      - test/built-ins/Atomics/wait/cannot-suspend-throws.js
    - [x] when [[CanBlock]] is true for an agent: call Atomics.wait in a web worker realm (or any realm outside of the main thread) and should not throw
      - test/built-ins/Atomics/wait/was-woken.js
8. Let block be buffer.[[ArrayBufferData]]. **NOT DIRECTLY OBSERVABLE**
9. Let offset be typedArray.[[ByteOffset]]. **NOT DIRECTLY OBSERVABLE**
10. Let indexedPosition be (i × 4) + offset. **NOT DIRECTLY OBSERVABLE**
11. Let WL be GetWaiterList(block, indexedPosition).
    - From _GetWaiterList_:
      - [ ] Return the WaiterList that is referenced by the pair (block, i).
12. Perform EnterCriticalSection(WL).
    - From _EnterCriticalSection_:
      - [ ] Wait until no agent is in the critical section for WL, then enter the critical section for WL (without allowing any other agent to enter).
       _(Note: will attempt to test this via  timeouts and sleeps, to ensure that only one agent is in the critical section for a given waitlist)_
13. Let w be ! AtomicLoad(typedArray, i). **NOT DIRECTLY OBSERVABLE**
14. If v is not equal to w, then a. Perform LeaveCriticalSection(WL). b.Return the String "not-equal"
    - [x] pass in a incorrect index and values for the typeArrary and assert that "not-equal" is returned
      - test/built-ins/Atomics/wait/value-not-equal.js
      - test/built-ins/Atomics/wait/good-views.js
15. Let W be AgentSignifier() **NOT DIRECTLY OBSERVABLE**
16. Perform AddWaiter(WL, W).
    - From _AddWaiter_:
      - [x] Add W to the end of the list of waiters in WL.
        - test/built-ins/Atomics/wait/waitlist-order-of-operations-is-fifo.js
17. Let awoken be Suspend(WL, W, t)
    - From _Suspend_:
      - [ ] Perform LeaveCriticalSection(WL) and suspend W for up to timeout milliseconds, performing the combined operation in such a way that a wakeup that arrives after the critical section is exited but before the suspension takes effect is not lost. W can wake up either because the timeout expired or because it was woken explicitly by another agent calling WakeWaiter(WL, W), and not for any other reasons at all.
        - test/built-ins/Atomics/wait/no-spurious-wakeup.js
      - [x] If W was woken explicitly by another agent calling WakeWaiter(WL, W), return true. (expected test out path for # 21)
         - test/built-ins/Atomics/wait/was-woken.js
      - [x] Return false. (expected test output path for #22)
        - test/built-ins/Atomics/wait/did-timeout.js
18. If awoken is true, then Assert: W is not on the list of waiters in WL. **NOT DIRECTLY OBSERVABLE**
19. Else, Perform RemoveWaiter(WL, W).
    - From _RemoveWaiter_:
      - [x] Remove W from the list of waiters in WL
20. Perform LeaveCriticalSection(WL). **NOT DIRECTLY OBSERVABLE**
21. If awoken is true, return the String "ok"
    - [x]  call Atomics.wait with a timeout, put an agent to sleep, and then call Atomics.wake before the timeout, and expect an output of "ok"
      - test/built-ins/Atomics/wait/was-woken-before-timeout.js
    - [x]  call Atomics.wait without a timeout, put an agent to sleep, and then call Atomics.wake before the timeout, and expect an output of "ok"
      - test/built-ins/Atomics/wait/was-woken.js
22. Return the String "timed-out"
    - [x] call Atomics.wait with a defined timeout of 1s and, after 1s assert that the all affected agents are not blocked and "timed-out" is returned.
      - test/built-ins/Atomics/wait/did-timeout.js
      - test/built-ins/Atomics/wait/good-views.js
