### ISSUE TITLE
Test Coverage Audit & Tracking for Atomics.wake 

### ISSUE THREAD

**Issue by nomadtechie** [tc39/test262#1472]
Below is a checklist for the observable items in the Atomics.wake spec: https://tc39.github.io/ecma262/#sec-atomics.wake.

I've mapped and noted the coverage of the current 17 test files and will be adding coverage for the remaining observables. I'll also be refactoring a few of the current tests because they cover too many spec observables in one test file, or partially cover the spec. 

Some of the observables I've listed below may not be directly testable via test262. I'll keep this list updated as I find unobservable abstractions and will mark them as NOT DIRECTLY OBSERVABLE

### Atomics.wake Static Property
- [x] Check Name
  - test/built-ins/Atomics/wake/name.js
- [x] Check length
  - test/built-ins/Atomics/wake/length.js
- [x] Check descriptor
  - test/built-ins/Atomics/wake/descriptor.js

### Atomics.wake( typedArray, index, count )
1. Let buffer be ? ValidateSharedIntegerTypedArray(typedArray, true)
  - [x] test for abrupt return if ValidateSharedIntegerTypedArray throws an error
    - test/built-ins/Atomics/wake/not-an-object-throws.js
    - test/built-ins/Atomics/wake/non-int32-typedarray-throws.js
    - test/built-ins/Atomics/wake/null-bufferdata-throws.js
    - test/built-ins/Atomics/wake/non-shared-bufferdata-throws.js
    - test/built-ins/Atomics/wake/not-a-typedarray-throws.js
  - **Observables from  *ValidateSharedIntegerTypedArray*:**
    - [x] if Type(typedArray) is not Object, throw a TypeError exception
      - test/built-ins/Atomics/wake/not-an-object-throws.js
      - **Covered but test cases cover multiple spec lines. Requires rework to isolate test cases:** test/built-ins/Atomics/wake/non-views.js
    - [x] If typedArray does not have a [[TypedArrayName]] internal slot, throw a TypeError exception
      - test/built-ins/Atomics/wake/not-a-typedarray-throws.js
    - [x] If typeName is not "Int32Array", throw a TypeError exception.
      - test/built-ins/Atomics/wake/non-int32-typedarray-throws.js
      - test/built-ins/Atomics/wake/shared-nonint-views.js
    - If IsSharedArrayBuffer(buffer) is false, throw a TypeError exception
      - test/built-ins/Atomics/wake/non-shared-int-views.js
    - **Observables from  *IsSharedArrayBuffer*:**
      - [x] If bufferData is null, return false. ( via setting [[ArrayBufferData]] to null)
        - test/built-ins/Atomics/wake/null-bufferdata-throws.js
      - [x] If bufferData is a Data Block, return false. (via creating a Data Block https://tc39.github.io/ecma262/#sec-data-blocks)
        - test/built-ins/Atomics/wake/nonshared-bufferdata-throws.js
2. Let i be ? ValidateAtomicAccess(typedArray, index)
    - [x]  test for abrupt return if ValidateAtomicAccess throws an error
      - test/built-ins/Atomics/wake/negative-index-throws.js
      - test/built-ins/Atomics/wake/symbol-for-index-throws.js
      - test/built-ins/Atomics/wake/out-of-range-index-throws.js
    - **Observables from *ValidateAtomicAccess*:**
        - Let accessIndex be ? ToIndex(requestIndex)
            - [x] abrupt return if ToIndex throws an error
              - test/built-ins/Atomics/wake/symbol-for-index-throws.js
              - test/built-ins/Atomics/wake/negative-index-throws.js
            - **Observables from ToIndex**: *(test cases limited to superficial tests which ensure ToIndex is called)*
              - [x] If value is undefined, let index be 0 and return index
                - test/built-ins/Atomics/wake/undefined-index-defaults-to-zero.js
              - [x] If integerIndex < 0, throw a RangeError exception.
                - test/built-ins/Atomics/wake/negative-index-throws.js
    - [x] If accessIndex ≥ length, throw a RangeError exception.
      - test/built-ins/Atomics/wake/out-of-range-index-throws.js
      - test/built-ins/Atomics/wake/bad-range.js
3. If count is undefined, let c be +∞.
  - [x] confirm that an undefined count wakes all the agents in the queue
    - test/built-ins/Atomics/wake/count-defaults-to-infinity-missing.js
    - test/built-ins/Atomics/wake/count-defaults-to-infinity-undefined.js
4. Else,
  - a. Let intCount be ? ToInteger(count).
    - [x] abrupt return when ToInteger throws an error
      - test/built-ins/Atomics/wake/count-throws-then-wake-throws.js
    - Let number be ? ToNumber(argument).
        - [x] abrupt return when ToNumber throws an error
          - test/built-ins/Atomics/wake/count-throws-then-wake-throws.js
    - [x] confirm that a Symbol count throws a TypeError exception.
      - test/built-ins/Atomics/wake/symbol-count-throws.js
    - [x] If number is NaN, return +0.
      - test/built-ins/Atomics/wake/count-nans.js
      - test/built-ins/Atomics/wake/wake-nan.js
    - [x] If number is +0, -0, +∞, or -∞, return number
  - b. Let c be max(intCount, 0).
    - [x] confirm -0, negative integer, and negative infinity result in a count of 0
      - test/built-ins/Atomics/wake/count-boundary-cases.js
      - test/built-ins/Atomics/wake/wake-negative.js
5. Let block be buffer.[[ArrayBufferData]] **NOT DIRECTLY OBSERVABLE**
6. Let offset be typedArray.[[ByteOffset]] **NOT DIRECTLY OBSERVABLE**
7. Let indexedPosition be (i × 4) + offset. **NOT DIRECTLY OBSERVABLE**
8. Let WL be GetWaiterList(block, indexedPosition).
  - **Observables from GetWaiterList:**
    - [x] Return the WaiterList that is referenced by the pair (block, i).
      - test/built-ins/Atomics/wake/wake-all-on-loc.js
9. Let n be 0
    - [x] confirm that calling wake when there are no waiting agents returns zero
      - test/built-ins/Atomics/wake/wake-with-no-agents-waiting.js
    - [x] confirm that calling wake with params that do not match any waiting agents returns zero
      - test/built-ins/Atomics/wake/wake-with-no-matching-agents-waiting.js
10. Perform EnterCriticalSection(WL).
  - **Observables from EnterCriticalSection:**
    - Wait until no agent is in the critical section for WL, then enter the critical section for WL (without allowing any other agent to enter). _(Note: will attempt to test this via  timeouts and sleeps, to ensure that only one agent is in the critical section for a given waitlist)_.
      - Untested
11. Let S be RemoveWaiters(WL, c).
  - **Observables from RemoveWaiters:**
    - Repeat, while c > 0 and S is not an empty List,
      - [x] confirm that the correct number of agents is removed from the WL
        - test/built-ins/Atomics/wake/wake-one.js
        - test/built-ins/Atomics/wake/wake-two.js
        - test/built-ins/Atomics/wake/wake-all.js
      - [x] confirm that a count of 0 does not remove any agents from the WL
        - test/built-ins/Atomics/wake/wake-zero.js
    - a. Let W be the first waiter in S,
    - b. Add W to the end of L.
    - c. Remove W from S.
    - d. Subtract 1 from c.
    - Return L.
      - [x] confirm that 1 agent removed from the count list decrements c by 1
        - test/built-ins/Atomics/wake/wake-in-order.js
      - [x] confirm that the agents are removed in the correct order FIFO
        - test/built-ins/Atomics/wake/wake-in-order.js
12. Repeat, while S is not an empty List,
  - a. Let W be the first agent in S.
  - b. Remove W from the front of S.
    - [x] confirm that the agents are removed in the correct order FIFO
      - test/built-ins/Atomics/wake/wake-in-order.js
  - c. Perform WakeWaiter(WL, W).
    - **Observables from WakeWaiter:**
      - Wake the agent W.
        - [x] confirm that an agent(s) in a waiting state is woken and no longer blocked
          - test/built-ins/Atomics/wake/wake-in-order.js
        - [x] confirm that waking an agent(s) that have already been woken is a noop
          - test/built-ins/Atomics/wake/wake-rewake-noop.js
  - d. Add 1 to n.
    - [x] confirm that waking a waiting agent(s) increments n by 1
      - test/built-ins/Atomics/wake/wake-in-order.js
    - confirm that waking an agent(s) that is NOT waiting is does not increment n by 1
      - Not sure if this is observable?
13. Perform LeaveCriticalSection(WL). **NOT DIRECTLY OBSERVABLE**
14. Return n.
  - [x] confirm that the correct number gets returned for the number of agents woken up
    - test/built-ins/Atomics/wake/wake-zero.js
    - test/built-ins/Atomics/wake/wake-one.js
    - test/built-ins/Atomics/wake/wake-two.js
    - test/built-ins/Atomics/wake/good-views.js
