### ISSUE TITLE
Meta: Moving to a `main` default branch.

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#2699]
I'd love to change this repo to use `main` as the default branch, rather than `master`. @GitHub says they are working on a feature that would help with some redirecting.

There are some challenges right now.

We have many orgs importing Test262 and still using the `master` branch to get the most recent updates. It's not easy to list them all here, or make sure they are all at least ready.

I tried syncing the branches through a GitHub Action, but [it fails pushing changes to a protected branch](https://github.com/tc39/test262/runs/866719536?check_suite_focus=true#step:3:1).

We rely on GitHub protected branches, to [at least set required workflows from PRs](https://github.com/tc39/test262#how-to-read-ci-results) as we have many workflows and we only require 2 to pass.

As you can see from the image below, I even tried the minimal settings from the "branch protection" but it still blocks syncing.

<img width="907" alt="Screen Shot 2020-07-13 at 1 17 10 PM" src="https://user-images.githubusercontent.com/301201/87350061-2f2d5180-c50c-11ea-9f2f-cca330b15bbf.png">

We have some options to set `main` branch as default, not in any order of preference:

0. Wait a bit more for @GitHub to release a redirecting feature
1.  Project admins **manually** update the master branch for a limited period (one month?). 
2. Remove the branch protections, let things sync through Actions workflow, update the readme file, "no required CI task" anymore.
3. Try out some automation to open PRs updating the master branch for a limited period, we've done that in the past (thanks to @nomadtechie).
4. Not update the master branch, let it stall.

---

For any non 0 option:

We should set a schedule to delete the `master` branch, ideally it should ceases to exist, but we can wait for the eventual redirecting feature GitHub should release. 

We can handle the existing PRs without many problems, regardless the option we set.

---

My favorite option is *1*, we would have a better time to identify major consumers of Test262 and help them updating.

For now I'm cc'ing some projects I know that are using, please let me know if there are more to add here. I'll check the boxes when they voice readiness for the change (here or through any channels).

Again, no specific order.

- [x] Test262.report (@rwaldron)
- [x] V8 (@syg)
- [x] SpiderMonkey (@codehag, @anba)
- [x] JSC (@kmiller68)
- [x] ChakraCore (@bterlson, ?)
- [x] Moddable XS (@phoddie) 
- [x] engine262 (@devsnek)
- [x] QuickJS (?)
- [x] GraalJS (?, maybe @gibson042?)
- [x] JSHint (@jugglinmike)
- [x] Acorn (@RReverser)
- [x] ESLint (@nzakas)
- [x] Babel (@nicolo-ribaudo)
- [x] TypeScript (@bterlson, ?)
- [x] Salesforce (@manuel-jasso, @caridy)
- [x] Kevin Gibbons (on behalf of _~half a dozen_ projects)

Anyone else?

**Comment by devsnek** [comment]
I'm good/ready/etc.

**Comment by rwaldron** [comment]
I'll get everything updated tomorrow

**Comment by leobalter** [comment]
As an update, there is already a workflow that updates the `master` branch after changes from the `main` branch (not the other way around). This only works when I lift the protections off for the `master` branch, which could happen when we eventually set `main` as default.

**Comment by bnb** [comment]
+1. You may also be interested in this: https://www.npmjs.com/package/retarget_prs

**Comment by leobalter** [comment]
Thanks @bnb, in this case we don't have many open PRs so it would be pretty easy to do it manually too. This might become handy within ECMA-262. cc @ljharb

**Comment by ljharb** [comment]
262 will likely wait for github's changes.

**Comment by mikesherov** [comment]
You probably want @rreverser for Acorn and @nzakas for ESLint

**Comment by manuel-jasso** [comment]
@leobalter We're ready for option 1

**Comment by leobalter** [comment]
Thanks @mikesherov!

**Comment by jugglinmike** [comment]
JSHint is ready for option 1.

(By the way: Esprima also uses Test262, but [they're set up to fetch from this repository by SHA](https://github.com/jquery/esprima/blob/d277380c4cf7a2ff3ba3499b6d82b126c9888d4a/package.json#L78), so this change shouldn't present any automation-related issues there.)

**Comment by nzakas** [comment]
ESLint doesn’t directly use test262, so we are set.

**Comment by RReverser** [comment]
Acorn links to a commit hash rather than a branch name, so we're good too.

**Comment by nicolo-ribaudo** [comment]
For Babel both 1 and 4 would work. cc @JLHwung

**Comment by mikesherov** [comment]
I have no skin in this game, but since I was originally tagged, I'd say Option 0 is non-ideal because it facilitates consumers to still reference master.

**Comment by ljharb** [comment]
@mikesherov the particular case that's important here is URLs, which can 301 to the new name, and might live in a place that can't be updated (from a locked/archived project, for example). Cool URLs don't change.

**Comment by leobalter** [comment]
Let's see if I can get some feedback from Mozilla as Gecko's [test262 import script does use the master branch](https://github.com/mozilla/gecko-dev/blob/92ef1e0f786000016c608243cac2bec2acb0e018/js/src/tests/test262-update.py), but it seems easy to address.

**Comment by leobalter** [comment]
I opened this bug for SpiderMonkey and perhaps I can patch it myself.

https://bugzilla.mozilla.org/show_bug.cgi?id=1652830

**Comment by leobalter** [comment]
I'm applying the changes today, matching option 1.

Here is what gonna happen:

1. Verify the `main` branch is up to date.
1. Set the default branch to `main` in the project settings.
1. Set branch protections for the `main` branch only. Those protections are relevant to PRs.
1. Set the head branch for the current open PRs to `main`. Post a comment on each for a heads up.
1. Verify the Actions workflow, currently it's supposed to update `master`. 
1. Project admins often verify the `master` branch for a limited period.
1. Mention this work at the TC39 meeting next week.
1. Last update to the `master` branch should be in 2020-08-14 (August 14th 2020).


After this date, we consider deleting the `master` branch. Links might get broken if @GitHub doesn't release a redirecting feature. IMO, it's a burden we can face.

**Comment by rwaldron** [comment]
I checked off QuickJS because that project is not open source, so we cannot know if the author ever updates, unless they tell us directly, and even then it doesn't matter because it's not verifiable.

**Comment by rwaldron** [comment]
I checked GraalJS because I've reviewed their repository and found no references to the test262 repo or to a branch named `master`.

@leobalter please close when you've reviewed these changes.

**Comment by leobalter** [comment]
I believe all the steps are complete but I failed to delete the master branch. Someone else with admin access would be able to do it and also remove the syncing circleci action. Please feel free to close this at any time.
